name: CI docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Build Docker image
      run: |
        cd my-app
        docker build -t my-image:1.0 .
    - name: Test Docker container
      run: |
        cd my-app
        docker run my-image:1.0 npm test
