name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Dependecies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Save version
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        
      - name: Increase version
        run: npm version patch
        
      - name: Push new version
        run: git push
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag nemopanu/Nemo:${{steps.version.outputs.tag}}
        
      - name: Push to Docker Hub
        run: docker push nemopanu/Nemo:${{steps.version.outputs.tag}}
