name: CI docker

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Build Docker image
      run: |
        cd my-app
        docker build -t react-image .
    - name: Build Docker image server
      run: |
        cd my-app/src/Swagger
        docker build -t node-server .     
    - name: Test Docker compose
      run: |
        cd my-app/src/Swagger
        docker-compose up
        docker-compose stop
